### ISSUE TITLE
Selection bugs/tasks

### ISSUE THREAD

**Issue by MingweiSamuel** [SudokuStudio/SudokuStudio#8]
- [x] Avoid <text> highlighting f9a8ec77fa76961142e4ba52a0fe3fd979d2d55b
- [x] Prevent selecting off-grid cells 730def2387f7a472b94dea48c28fa420b98bc083
- [x] Allow diagonal drags by using circular hitbox 730def2387f7a472b94dea48c28fa420b98bc083
- [x] Clicking on cell (without drag) toggles f9a8ec77fa76961142e4ba52a0fe3fd979d2d55b
- [x] Shift/ctrl/alt click modes (see below) f9a8ec77fa76961142e4ba52a0fe3fd979d2d55b
  -  [x] Handle meta (mac command) key as ctrl bdbcab71004939716456f98d81df6d6ba3eb384f
- [x] `e.preventDefault()` or something to handle mac CMD+click showing context menu f9a8ec77fa76961142e4ba52a0fe3fd979d2d55b
- [x] Doubleclick to select matching cells
- [x] Touch support

```
David Clamage (Rangsk): ok so the design I like for ctrl+click is as follows (which is what CTC does):
1) The first cell clicked determines if it's in additive or subtractive mode.
If the cell is already highlighted, it's subtractive, otherwise additive.
2) Dragging through other cells applies the add or subtract based on the decision in #1.

David Clamage (Rangsk): I also like doing shift+click for additive only,
and alt+click for subtraction only, but that's different from what others do.
```

**Comment by DancingGrumpyCat** [comment]
I quite like David's suggestion—and how CtC handles it

**Comment by wooferzfg** [comment]
For double clicking to select matching cells, here is CTC's behavior:

## Choosing criteria
To determine the criteria (i.e. filled, center mark, corner mark, color) by which to find matching cells:
- Does the selected cell contain the currently selected numpad tool (e.g. corner marks)? If so, use the currently selected tool as the criteria.
- Otherwise, choose the highest priority tool that the selected cell contains. Priority order:
  1. filled
  2. color
  3. center mark
  4. corner mark

For example, if the cell is colored, contains a center mark, and contains a corner mark:
- If the currently selected tool is "filled", then "color" is chosen as the criteria.
- If the currently selected tool is "corner mark", then "corner mark" is chosen as the criteria.

## Determining matching cells
To determine whether a cell matches the selected cell, all of the cells in the grid are filtered, depending on the criteria:
- Filled: The cell is filled and contains the same digit as the selected cell.
- Color: At least one of the cell's colors matches at least one of the colors of the selected cell.
  - For example, if the selected cell is yellow/green, then green, yellow, yellow/green, and green/red would all match.
  - The cell may also contain a digit, center marks, or corner marks.
- Center mark: The cell's center marked digits contain at least all of the digits that are center marked in the selected cell.
  - For example, if the selected cell has 35 center marked, then 35 and 358 would match, but 3 and 58 would not.
  - The cell may also contain a color or corner marks.
- Corner mark: At least one of the cell's corner marked digits matches at least of the corner marked digits of the selected cell.
  - For example, if the selected cell has 68 corner marked, then 6, 8, 26, and 589 would all match.
  - The cell may also contain a color or center marks.

**Comment by dclamage** [comment]
Additional feature idea: Clicking on a numpad button with nothing selected selects all cells with that value marked in some way (given, center, corner) or if in color mode, selects any cell with that color.

**Comment by wooferzfg** [comment]
I implemented double clicking in https://github.com/SudokuStudio/SudokuStudio/commit/1309692283e7ae876a72f7d474afa9f6a03d259b.

**Comment by wooferzfg** [comment]
Added touch support in https://github.com/SudokuStudio/SudokuStudio/commit/48b37b867cfe370165c177dcf8011086b3530967.
